
# Google Analytics Tracking Codes
sitemap-analytics-code: "?utm_source=sitemap&utm_medium=referral&utm_campaign=sitemap"
navlinks-analytics-code: "?utm_source=MainNav&utm_medium=referral&utm_campaign=MainNav+to+Template"
blognav-to-templates-analytics-code: "?utm_source=Blognav&utm_medium=referral&utm_campaign=BlogNav+to+Template"
homepage-analytics-code: "?utm_source=Homepage&utm_medium=referral&utm_campaign=Homepage+to+Template"
