language: node_js
git:
  depth: 3
node_js:
  - "0.10"

notifications:
  email: false

before_install:
  - gem install jekyll rouge --no-document --no-ri --no-rdoc
  - npm install -g grunt-cli bower
  - bower install
