# Site settings
title: Your awesome title
email: "lubomirgeorgievgeorgiev[at]gmail.com"
description: "Your description here."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/

paginate: 7

# Files to be ignored by Jekyll when compiling
exclude:
  - "*.less"
  - "*.xml"
  - "node_modules"