## Site settings ##
title: Your awesome title
email: "lubomirgeorgievgeorgiev[at]gmail.com"
author: "Lubomir Georgiev - Любомир Георгиев"
description: "Free HTML Web Templates. The place where you can download web templates just for free."
baseurl: ""
url: "http://freetemplatesdownload.info"
encoding:         UTF-8

destination:      ./_SITE_COMPILED


## Build settings ##
markdown: kramdown
permalink: /:categories/:title/

# paginate: 7

# Files to be ignored by Jekyll when compiling
exclude:
  - "*.less"
  - "*.xml"
  - "node_modules"
  - "README.md"
  - "package.json"
  - "gruntfile.js"
  - "BACKUP"
  - "LICENSE"
  - "blog/EXPLANATION.txt"

# Google Analytics Tracking Codes
sitemap-analytics-code: "?utm_source=sitemap&utm_medium=referral&utm_campaign=sitemap"
navlinks-analytics-code: "?utm_source=MainNav&utm_medium=referral&utm_campaign=MainNav+to+Template"
homepage-analytics-code: "?utm_source=Homepage&utm_medium=referral&utm_campaign=Homepage+to+Template"