# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: jekyllrb
description: Free HTML Web Templates. The place where you can download web templates just for free.
author: Lubomir Georgiev
email: lubomirgeorgievgeorgiev@gmail.com

url: "http://freetemplatesdownload.info"
github-repository: "https://github.com/LubomirGeorgiev/freetemplatesdownload.info"

permalink: /:categories/:title/

# Grunt handles images and assets.
exclude: ['images', 'css', '*.css', 'js', '**.less', 'less','blog/**.txt', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', '**.map']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: rouge
